/** @type {import("@stackbit/types").Model} */
export default {
  name: "site_configuration",
  type: "data",
  filePath: "src/content/site-configuration.json",
  fields: [
    {
      name: "primaryColor",
      type: "enum",
      required: true,
      default: "blue",
      options: [
        { label: "Bronze", value: "bronze" },
        { label: "Gold", value: "gold" },
        { label: "Brown", value: "brown" },
        { label: "Orange", value: "orange" },
        { label: "Tomato", value: "tomato" },
        { label: "Red", value: "red" },
        { label: "Ruby", value: "ruby" },
        { label: "Crimson", value: "crimson" },
        { label: "Pink", value: "pink" },
        { label: "Plum", value: "plum" },
        { label: "Purple", value: "purple" },
        { label: "Violet", value: "violet" },
        { label: "Iris", value: "iris" },
        { label: "Indigo", value: "indigo" },
        { label: "Blue", value: "blue" },
        { label: "Cyan", value: "cyan" },
        { label: "Teal", value: "teal" },
        { label: "Jade", value: "jade" },
        { label: "Green", value: "green" },
        { label: "Grass", value: "grass" },
        { label: "Sky", value: "sky" },
        { label: "Mint", value: "mint" },
        { label: "Lime", value: "lime" },
        { label: "Yellow", value: "yellow" },
        { label: "Amber", value: "amber" },
      ],
    },
    {
      name: "grayScale",
      type: "enum",
      required: true,
      default: "gray",
      options: [
        { label: "Gray", value: "gray" },
        { label: "Mauve", value: "mauve" },
        { label: "Slate", value: "slate" },
        { label: "Sage", value: "sage" },
        { label: "Olive", value: "olive" },
        { label: "Sand", value: "sand" },
      ],
    },
    {
      name: "textScale",
      type: "enum",
      required: true,
      default: "gray",
      options: [
        { label: "Gray", value: "grayScale" },
        { label: "Primary", value: "primary" },
      ],
    },
    {
      name: "containerRadius",
      type: "enum",
      required: false,
      options: [
        { label: "Extra Small", value: ".25rem" },
        { label: "Small", value: ".375rem" },
        { label: "Medium", value: ".5rem" },
        { label: "Large", value: ".75rem" },
        { label: "Extra Large", value: "1rem" },
      ],
    },
    {
      name: "controlRadius",
      type: "enum",
      required: false,
      options: [
        { label: "Extra Small", value: ".25rem" },
        { label: "Small", value: ".375rem" },
        { label: "Medium", value: ".5rem" },
        { label: "Large", value: ".75rem" },
        { label: "Extra Large", value: "1rem" },
        { label: "Full", value: "9999px" },
      ],
    },
    {
      name: "headingFont",
      type: "enum",
      required: true,
      default: "system-ui",
      options: [
        { label: "System UI", value: "system-ui" },
      ],
    },
    {
      name: "bodyFont",
      type: "enum",
      required: true,
      default: "system-ui",
      options: [
        { label: "System UI", value: "system-ui" }
      ],
    },
  ],
};
